// AUTOGENERATED from types.tsv col 0 (Caller) + col 8 (ResetFactoryFunc)
#pragma once
#include <stdint.h>
#include <string.h>
struct TypeCaller {
    const char* name;
    uint32_t    callerVA; // Atvaark VA, base 0x400000
    uint32_t    resetVA;
};
static const TypeCaller g_typeCallers[] = {
    { "sEnemyManager", 0x013278EA, 0x013876B0 },
    { "sLockOnManager", 0x01328157, 0x01387810 },
    { "sNpcManager", 0x013283FA, 0x013878A0 },
    { "sPawnManager", 0x0132853A, 0x013878E0 },
    { "sPlayerManager", 0x0132859A, 0x013878F0 },
    { "sRecognition", 0x01328817, 0x01387980 },
    { "sUnit", 0x0137B3CA, 0x01395EB0 },
    { "sUnitSearchManager", 0x0132770A, 0x01387650 },
    { "uCharacterBase", 0x0133FE2A, 0x0138C190 },
    { "uCmc", 0x0136BEDA, 0x01392C90 },
    { "uEm0100", 0x013446BA, 0x0138CC30 },
    { "uEm0101", 0x013468FA, 0x0138D4C0 },
    { "uEm0200", 0x0134788A, 0x0138D600 },
    { "uEm0500", 0x0134C2EA, 0x0138E090 },
    { "uEm0900", 0x0135025A, 0x0138E960 },
    { "uEnemy", 0x01366F1A, 0x01391970 },
    { "uHumanEnemy", 0x0136CEBA, 0x01392FB0 },
    { "uNpc", 0x0136CF7A, 0x01392FD0 },
    { "uPawnIntel", 0x01335037, 0x0138A1C0 },
    { "uPlayer", 0x0136BF9A, 0x01392CB0 },
    { nullptr, 0, 0 }
};
inline const TypeCaller* FindCaller(const char* n){
    if(!n) return nullptr;
    for(const TypeCaller* c=g_typeCallers; c->name; ++c) if(!strcmp(c->name,n)) return c;
    return nullptr;
}
