#!/usr/bin/env python3
"""gen_default_ini.py — вшивает ddda_entities.ini в заголовок.

Зачем: DLL должна СОЗДАТЬ файл при первом запуске, если его нет.
Значит содержимое по умолчанию обязано лежать внутри кода.

Чтобы файл и вшитая копия не разъехались, заголовок генерируется
из самого ini, а не пишется руками.

    python3 tools/gen_default_ini.py
"""
import os

SRC = "ddda_entities.ini"
DST = "src/DefaultEntitiesIni.h"

def esc(line: str) -> str:
    return line.replace('\\', '\\\\').replace('"', '\\"')

def main():
    with open(SRC, encoding="utf-8") as f:
        lines = f.read().split("\n")
    while lines and not lines[-1].strip():
        lines.pop()

    out = []
    out.append("#pragma once")
    out.append("// AUTOGENERATED from ddda_entities.ini by tools/gen_default_ini.py")
    out.append("// НЕ РЕДАКТИРОВАТЬ РУКАМИ: правьте ddda_entities.ini и перегенерируйте.")
    out.append("//")
    out.append("// Содержимое по умолчанию. Пишется на диск, если файла нет.")
    out.append("// ВАЖНО: требует /utf-8 в настройках компилятора, иначе кириллица")
    out.append("// в комментариях превратится в мусор.")
    out.append("")
    out.append("static const char* const kDefaultEntitiesIni[] = {")
    for ln in lines:
        out.append('    "%s\\r\\n",' % esc(ln))
    out.append("    nullptr")
    out.append("};")
    out.append("")

    os.makedirs(os.path.dirname(DST), exist_ok=True)
    with open(DST, "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print("%s -> %s  (%d строк)" % (SRC, DST, len(lines)))

if __name__ == "__main__":
    main()
