#!/usr/bin/env python3
"""Generate src/ActMap.Generated.h — per-enemy FSM action states.

Every MT Framework enemy action state is a registered type named
`cEm<ID>Act<Name>` (e.g. cEm0100ActThreatHowl = the goblin's taunt howl).
The instance vtable RVA identifies the state at runtime: read the current
action object pointer, deref [0], compare against these RVAs.

This is the map that turns "some FSM state" into "the goblin is taunting".
"""
import re, sys, collections

# Порядок важен: возвращается ПЕРВАЯ совпавшая категория.
#
# 'guard' поднят выше 'attack' намеренно: у гоблина есть щитовые действия
# вида cEm0100ActCSldBPress — по слову Press это выглядит как атака, но
# на деле это давление щитом, то есть защита.
#
# Список 'attack' пополнен по разбору всех 812 действий 35 видов
# (19.08.2026): прежний вариант терял Atk (без 'c'), Bite, Claw, Trample,
# Stomp и Breath — то есть почти все атаки крупных монстров, у которых
# нет слова Attack в имени вовсе.
CATEGORIES = [
    ('taunt',  ('Howl', 'Threat', 'PartyDance', 'Horn', 'JumpJoy', 'Appeal')),
    ('death',  ('Die', 'DeadBody', 'Dead')),
    ('damage', ('ActDmg',)),
    ('guard',  ('Grd', 'Guard', 'Sld')),
    ('attack', ('Atck', 'Attack', 'Atk', 'Kick', 'Throw', 'Thrust', 'Swing',
                'Assassin', 'Bite', 'Claw', 'Trample', 'Stomp', 'Breath',
                'Tail', 'Punch', 'Slash', 'Shot', 'Beam', 'Fire', 'Spit',
                'Charge',
                # маги и бесплотные: слова Attack в именах нет вовсе
                'Magic', 'Mgc', 'Missile', 'Combo', 'DeathTouch', 'Absorb')),
    ('wait',   ('Wait',)),
    ('move',   ('Walk', 'Dash', 'Run', 'Jump', 'Tumble', 'Move', 'Turn')),
]

# Имена «получаю удар», которые по глаголу похожи на атаку. Проверяются
# ПЕРВЫМИ: cEm0100ActChargeKicked — это когда пинают тебя, а не ты.
RECEIVING = ('Kicked', 'Guarded', 'Catched', 'Caught', 'Grabbed', 'Thrown',
             'Pressed', 'Bitten', 'Damaged')

def categorize(name):
    if any(k in name for k in RECEIVING):
        return 'damage'
    for cat, keys in CATEGORIES:
        if any(k in name for k in keys):
            return cat
    return 'other'

def main(atlas='src/TypeAtlas.Generated.h', out='src/ActMap.Generated.h'):
    src = open(atlas, encoding='utf-8').read()
    # cEm0100ActDie  и  cEm5101_00ActDie  (подтипы через _NN)
    entries = []
    pat = (r'\{ "(cEm(\d{4})(?:_\d+)?Act([A-Za-z0-9_]*))", '
           r'(0x[0-9A-F]+), (0x[0-9A-F]+), (\d+), (\d+) \}')
    for m in re.finditer(pat, src):
        full, emid, act, fr, vt, size, tid = m.groups()
        if not act:
            continue
        entries.append((full, emid, act, vt, int(size)))
    entries.sort(key=lambda e: (e[1], e[2]))

    by_em = collections.Counter(e[1] for e in entries)
    L = []
    L.append('// ActMap.Generated.h — AUTOGENERATED from TypeAtlas')
    L.append('// python3 tools/generate_act_map.py')
    L.append('// FSM-состояния врагов: cEm<ID>Act<Name> -> instance vtable RVA')
    L.append('#pragma once')
    L.append('#include <stdint.h>')
    L.append('')
    L.append('namespace ActMap {')
    L.append('')
    L.append('struct Act {')
    L.append('    const char* name;      // короткое имя состояния, напр. "ThreatHowl"')
    L.append('    const char* fullName;  // cEm0100ActThreatHowl')
    L.append('    uint16_t    emId;      // 100 = uEm0100')
    L.append('    uint32_t    vtRVA;     // vtable RVA; сравнивать с *(uint32_t*)actObj - moduleBase')
    L.append('    uint16_t    size;')
    L.append('    const char* category;  // taunt/death/damage/attack/wait/move/guard/other')
    L.append('};')
    L.append('')
    L.append('static const int kCount = %d;' % len(entries))
    L.append('static const Act kActs[] = {')
    for full, emid, act, vt, size in entries:
        L.append('    { "%s", "%s", %d, %s, %d, "%s" },' %
                 (act, full, int(emid), vt, size, categorize(act)))
    L.append('};')
    L.append('')
    L.append('inline const Act* FindByVt(uint32_t rva) {')
    L.append('    for (int i = 0; i < kCount; ++i)')
    L.append('        if (kActs[i].vtRVA == rva) return &kActs[i];')
    L.append('    return nullptr;')
    L.append('}')
    L.append('')
    L.append('// Поиск по ИМЕНИ класса. Именно он нужен в рантайме: vtRVA в этой')
    L.append('// таблице — factory vtable и для сравнения с живым объектом')
    L.append('// непригодна (см. шапку файла). Имя живого действия берётся')
    L.append('// у самой игры через DTI.')
    L.append('inline const Act* FindByName(const char* fullName) {')
    L.append('    if (!fullName) return nullptr;')
    L.append('    for (int i = 0; i < kCount; ++i) {')
    L.append('        const char* a = kActs[i].fullName;')
    L.append('        int k = 0;')
    L.append('        while (a[k] && a[k] == fullName[k]) ++k;')
    L.append('        if (!a[k] && !fullName[k]) return &kActs[i];')
    L.append('    }')
    L.append('    return nullptr;')
    L.append('}')
    L.append('')
    L.append('// Атака ли это действие. Неизвестное имя — НЕ атака: лучше')
    L.append('// пропустить правку, чем ускорить существу падение или смерть.')
    L.append('inline bool NameIsAttack(const char* fullName) {')
    L.append('    const Act* a = FindByName(fullName);')
    L.append('    if (!a) return false;')
    L.append("    const char* c = a->category;")
    L.append("    return c[0]=='a' && c[1]=='t' && c[2]=='t' && c[3]=='a'")
    L.append("        && c[4]=='c' && c[5]=='k' && c[6]==0;")
    L.append('}')
    L.append('')
    L.append('inline bool IsCategory(uint32_t rva, const char* cat) {')
    L.append('    const Act* a = FindByVt(rva);')
    L.append('    if (!a) return false;')
    L.append('    for (int i = 0; cat[i] || a->category[i]; ++i)')
    L.append('        if (cat[i] != a->category[i]) return false;')
    L.append('    return true;')
    L.append('}')
    L.append('')
    L.append('} // namespace ActMap')
    open(out, 'w', encoding='utf-8').write('\n'.join(L) + '\n')

    print('%s: %d состояний, %d видов врагов' % (out, len(entries), len(by_em)))
    cats = collections.Counter(categorize(e[2]) for e in entries)
    print('по категориям:', dict(cats))
    print('топ видов:', by_em.most_common(8))

if __name__ == '__main__':
    main(*sys.argv[1:])
