#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
generate_bestiary.py — Грамотное использование types.tsv в dinput8.dll моде
Читает resources/types.tsv и генерирует src/EnemyTypes.Generated.h
Запускать: python tools/generate_bestiary.py
"""
import csv, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TSV  = os.path.join(ROOT, "resources", "types.tsv")
OUT  = os.path.join(ROOT, "src", "EnemyTypes.Generated.h")

# bestiary.py -> bestiaryId mapping (упрощенно, хардкодим 72 имени из BestiaryData.h)
BESTIARY_NAMES = {
    # bestiaryId: (name, family, guess_uEm)
    0: ("Goblins","Goblin","uEm0100"), 1: ("Hobgoblins","Goblin","uEm0101"), 2: ("Grimgoblins","Goblin","uEm0102"),
    3: ("Wolves","Wolf","uEm0200"), 4: ("Direwolves","Wolf","uEm0201"), 5: ("Hellhounds","Wolf","uEm0202"),
    6: ("Skeletons","Skeleton","uEm0500"), 7: ("Skeleton Knights","Skeleton","uEm0501"), 8: ("Skeleton Lords","Skeleton","uEm0502"),
    9: ("Skeleton Mages","Skeleton","uEm0503"), 10: ("Skeleton Sorcerers","Skeleton","uEm0504"),
    11: ("Saurians","Saurian","uEm0400"), 12: ("Sulfur Saurians","Saurian","uEm0401"), 13: ("Geo Saurians","Saurian","uEm0402"), 14: ("Saurian Sages","Saurian","uEm0403"),
    15: ("Undead","Undead","uEm0600"), 16: ("Stout Undead","Undead","uEm0601"), 17: ("Undead Warriors","Undead","uEm0602"), 18: ("Giant Undead","Undead","uEm0603"),
    19: ("Harpies","Harpy","uEm0700"), 20: ("Snow Harpies","Harpy","uEm0701"), 21: ("Succubi","Harpy","uEm0702"),
    22: ("Gargoyles","Gargoyle","uEm0900"), 23: ("Phantoms","Ghost","uEm1200?"), 24: ("Phantasms","Ghost","uEm1201?"), 25: ("Specters","Ghost","uEm??"),
    29: ("Cyclopes","Cyclops","uEm2000"), 30: ("Ogres","Ogre","uEm2001?"), 31: ("Golems","Golem","uEm5000"), 33: ("Chimeras","Chimera","uEm5300"), 35: ("Hydras","Hydra","uEm5400"),
    37: ("Griffins","Griffin","uEm5800"), 38: ("Cockatrices","Cockatrice","uEm5801"), 39: ("Evil Eyes","EvilEye","uEm5900"), 41: ("Wights","Wight","uEm6000"),
    43: ("The Dragon (Grigori)","Dragon","uEm6001"), 45: ("Drakes","Dragon","uEm6002?"),
}

def load_tsv():
    entries = {}
    # Кастомные gid для типов у которых в TSV gid 0 но нужен distinct id (люди)
    custom_gid = {"uHumanEnemy": 0xE0, "sHumanEnemyManager": 0xE1}
    with open(TSV, encoding='utf-8') as f:
        f.readline() # skip header with duplicate Unknown
        for line in f:
            p = line.strip().split('\t')
            if len(p) < 10: continue
            name = p[2]
            gid = int(p[5])  # 6-я колонка = groupId (первый Unknown!)
            vtable = p[9]
            factory = p[1]
            caller = p[0]
            size = p[4]
            if name in custom_gid:
                gid = custom_gid[name]
                entries[name] = (gid, vtable, factory, caller, size)
            elif name.startswith("uEm") and gid != 0:
                entries[name] = (gid, vtable, factory, caller, size)
    return entries

def main():
    entries = load_tsv()
    print(f"Loaded {len(entries)} uEm types with gid!=0")
    # Покажем сколько из BestiaryData.h имеют 0xFF
    sorted_by_gid = sorted(entries.items(), key=lambda kv: kv[1][0])

    with open(OUT, 'w', encoding='utf-8') as o:
        o.write("// EnemyTypes.Generated.h — AUTOGENERATED from resources/types.tsv\n")
        o.write("// Не редактировать вручную! Перегенерить: python tools/generate_bestiary.py\n")
        o.write("// Источник: Atvaark/DragonsDogma.Research types.tsv\n")
        o.write("// Колонки TSV: Caller | FactoryPointer | FactoryName | Allocator | Size | groupId | unk | unk | ResetFunc | FactoryVtable\n")
        o.write("#pragma once\n#include <stdint.h>\n\n")
        o.write("struct EnemyTypeInfo {\n")
        o.write("    const char* uEmName;   // FactoryName (uEmXXXX)\n")
        o.write("    uint8_t     groupId;   // types.tsv col 5 == targetBase[0x2D] в damage-хуке\n")
        o.write("    uint32_t    vtableRVA; // FactoryVtable - 0x400000 (для сравнения *(void**)enemyPtr)\n")
        o.write("    uint32_t    factoryRVA;// FactoryPointer - 0x400000\n")
        o.write("    uint32_t    size;      // Размер объекта\n")
        o.write("};\n\n")
        o.write("inline uint32_t RVA(uint32_t absAddr){ return absAddr - 0x400000; }\n\n")
        o.write("static const EnemyTypeInfo g_enemyTypes[] = {\n")
        for name,(gid,vt,fp,caller,size) in sorted_by_gid:
            vt_rva = int(vt,16) - 0x400000
            fp_rva = int(fp,16) - 0x400000
            o.write(f'    {{"{name}", 0x{gid:02X}, 0x{vt_rva:06X}, 0x{fp_rva:06X}, {size}}}, // vt={vt} fp={fp}\n')
        o.write("    {nullptr, 0, 0, 0, 0}\n};\n\n")
        o.write("// Быстрый поиск по groupId (для CombatIntel)\n")
        o.write("inline const EnemyTypeInfo* FindByGroupId(uint8_t gid){\n")
        o.write("    for(auto *e=g_enemyTypes; e->uEmName; ++e) if(e->groupId==gid) return e;\n")
        o.write("    return nullptr;\n}\n")
        o.write("// Точный поиск по VTable (для различения Goblin vs Hobgoblin, gid=5 общий)\n")
        o.write("inline const EnemyTypeInfo* FindByVTable(uint32_t vtableRVA){\n")
        o.write("    for(auto *e=g_enemyTypes; e->uEmName; ++e) if(e->vtableRVA==vtableRVA) return e;\n")
        o.write("    return nullptr;\n}\n")
        o.write("// Runtime helper: получить RVA vtable из живого объекта\n")
        o.write("// uint32_t vt = *(uint32_t*)enemyPtr - base; -> FindByVTable(vt)\n")
    print(f"Wrote {OUT}")

if __name__ == "__main__":
    main()
    # Также генерим Bestiary.Generated.h если есть шаблон (см. src/Bestiary.Generated.h)
    print("Note: Bestiary.Generated.h уже сгенерирован отдельно (см. docs/TYPES_TSV_WALL_BREAKTHROUGH.md)")
    print("Для полной перегенерации запусти: python tools/generate_bestiary.py && python tools/gen_bestiary_complete.py")
