#!/usr/bin/env python3
"""Generate src/ActMap.Generated.h — per-enemy FSM action states.

Every MT Framework enemy action state is a registered type named
`cEm<ID>Act<Name>` (e.g. cEm0100ActThreatHowl = the goblin's taunt howl).
The instance vtable RVA identifies the state at runtime: read the current
action object pointer, deref [0], compare against these RVAs.

This is the map that turns "some FSM state" into "the goblin is taunting".
"""
import re, sys, collections

CATEGORIES = [
    ('taunt',  ('Howl', 'Threat', 'PartyDance', 'Horn', 'JumpJoy', 'Appeal')),
    ('death',  ('Die', 'DeadBody', 'Dead')),
    ('damage', ('ActDmg',)),
    ('attack', ('Atck', 'Attack', 'Kick', 'Throw', 'Thrust', 'Swing', 'Assassin')),
    ('wait',   ('Wait',)),
    ('move',   ('Walk', 'Dash', 'Run', 'Jump', 'Tumble', 'Move', 'Turn')),
    ('guard',  ('Grd', 'Guard', 'Sld')),
]

def categorize(name):
    for cat, keys in CATEGORIES:
        if any(k in name for k in keys):
            return cat
    return 'other'

def main(atlas='src/TypeAtlas.Generated.h', out='src/ActMap.Generated.h'):
    src = open(atlas, encoding='utf-8').read()
    # cEm0100ActDie  и  cEm5101_00ActDie  (подтипы через _NN)
    entries = []
    pat = (r'\{ "(cEm(\d{4})(?:_\d+)?Act([A-Za-z0-9_]*))", '
           r'(0x[0-9A-F]+), (0x[0-9A-F]+), (\d+), (\d+) \}')
    for m in re.finditer(pat, src):
        full, emid, act, fr, vt, size, tid = m.groups()
        if not act:
            continue
        entries.append((full, emid, act, vt, int(size)))
    entries.sort(key=lambda e: (e[1], e[2]))

    by_em = collections.Counter(e[1] for e in entries)
    L = []
    L.append('// ActMap.Generated.h — AUTOGENERATED from TypeAtlas')
    L.append('// python3 tools/generate_act_map.py')
    L.append('// FSM-состояния врагов: cEm<ID>Act<Name> -> instance vtable RVA')
    L.append('#pragma once')
    L.append('#include <stdint.h>')
    L.append('')
    L.append('namespace ActMap {')
    L.append('')
    L.append('struct Act {')
    L.append('    const char* name;      // короткое имя состояния, напр. "ThreatHowl"')
    L.append('    const char* fullName;  // cEm0100ActThreatHowl')
    L.append('    uint16_t    emId;      // 100 = uEm0100')
    L.append('    uint32_t    vtRVA;     // vtable RVA; сравнивать с *(uint32_t*)actObj - moduleBase')
    L.append('    uint16_t    size;')
    L.append('    const char* category;  // taunt/death/damage/attack/wait/move/guard/other')
    L.append('};')
    L.append('')
    L.append('static const int kCount = %d;' % len(entries))
    L.append('static const Act kActs[] = {')
    for full, emid, act, vt, size in entries:
        L.append('    { "%s", "%s", %d, %s, %d, "%s" },' %
                 (act, full, int(emid), vt, size, categorize(act)))
    L.append('};')
    L.append('')
    L.append('inline const Act* FindByVt(uint32_t rva) {')
    L.append('    for (int i = 0; i < kCount; ++i)')
    L.append('        if (kActs[i].vtRVA == rva) return &kActs[i];')
    L.append('    return nullptr;')
    L.append('}')
    L.append('')
    L.append('inline bool IsCategory(uint32_t rva, const char* cat) {')
    L.append('    const Act* a = FindByVt(rva);')
    L.append('    if (!a) return false;')
    L.append('    for (int i = 0; cat[i] || a->category[i]; ++i)')
    L.append('        if (cat[i] != a->category[i]) return false;')
    L.append('    return true;')
    L.append('}')
    L.append('')
    L.append('} // namespace ActMap')
    open(out, 'w', encoding='utf-8').write('\n'.join(L) + '\n')

    print('%s: %d состояний, %d видов врагов' % (out, len(entries), len(by_em)))
    cats = collections.Counter(categorize(e[2]) for e in entries)
    print('по категориям:', dict(cats))
    print('топ видов:', by_em.most_common(8))

if __name__ == '__main__':
    main(*sys.argv[1:])
