// Bestiary.Generated.h — AUTOGENERATED — DO NOT EDIT MANUALLY
// Merge: resources/types.tsv (groupId/vtable) + resources/bestiary.py (bestiaryId/FlagID) + src/BestiaryData.h (mStudyIdx)
// Regen: python tools/generate_bestiary.py --bestiary  (TODO)
#pragma once
#include "EnemyTypes.Generated.h"

struct BestiaryEntryEx {
    int bestiaryId;
    const char* name;
    const char* family;
    uint8_t groupId; // from types.tsv, 0xFF if not in TSV (needs CT scan)
    int mStudyIdx;   // -1 = unknown, else index in mStudyFlag[322]
    const char* uEm; // primary uEmXXXX from types.tsv
    uint32_t vtableRVA;
};

static BestiaryEntryEx g_bestiaryEx[] = {
    { 0, "Goblins", "Goblin", 0x05,  4, "uEm0100", 0x11A0474}, // from types.tsv uEm0100 vt=0x15a0474
    { 1, "Hobgoblins", "Goblin", 0x05, -1, "", 0}, // TODO: needs types.tsv/CT scan
    { 2, "Grimgoblins", "Goblin", 0x05, -1, "", 0}, // TODO: needs types.tsv/CT scan
    { 3, "Wolves", "Wolf", 0x08,  3, "uEm0200", 0x11A55F0}, // from types.tsv uEm0200 vt=0x15a55f0
    { 4, "Direwolves", "Wolf", 0x09, -1, "uEm0201", 0x11A5908}, // from types.tsv uEm0201 vt=0x15a5908
    { 5, "Hellhounds", "Wolf", 0x0A, -1, "uEm0202", 0x11A5C20}, // from types.tsv uEm0202 vt=0x15a5c20
    { 6, "Skeletons", "Skeleton", 0x1B,  8, "uEm0500", 0x11AE3B4}, // from types.tsv uEm0500 vt=0x15ae3b4
    { 7, "Skeleton Knights", "Skeleton", 0x1C, -1, "uEm0501", 0x11AE6D4}, // from types.tsv uEm0501 vt=0x15ae6d4
    { 8, "Skeleton Lords", "Skeleton", 0x1D, -1, "uEm0502", 0x11AE9F4}, // from types.tsv uEm0502 vt=0x15ae9f4
    { 9, "Skeleton Mages", "Skeleton", 0x1E, -1, "uEm0503", 0x11AED14}, // from types.tsv uEm0503 vt=0x15aed14
    {10, "Skeleton Sorcerers", "Skeleton", 0x1F, -1, "uEm0504", 0x11AF034}, // from types.tsv uEm0504 vt=0x15af034
    {11, "Saurians", "Saurian", 0x0F, 11, "uEm0400", 0x11A9ED4}, // from types.tsv uEm0400 vt=0x15a9ed4
    {12, "Sulfur Saurians", "Saurian", 0x12, -1, "uEm0401", 0x11A9EDC}, // from types.tsv uEm0401 vt=0x15a9edc
    {13, "Geo Saurians", "Saurian", 0x15, -1, "uEm0402", 0x11A9EE4}, // from types.tsv uEm0402 vt=0x15a9ee4
    {14, "Saurian Sages", "Saurian", 0x18, -1, "uEm0403", 0x11A9EEC}, // from types.tsv uEm0403 vt=0x15a9eec
    {15, "Undead", "Undead", 0x20, 16, "uEm0600", 0x11B1D4C}, // from types.tsv uEm0600 vt=0x15b1d4c
    {16, "Stout Undead", "Undead", 0x21, -1, "uEm0601", 0x11B2074}, // from types.tsv uEm0601 vt=0x15b2074
    {17, "Undead Warriors", "Undead", 0x22, -1, "uEm0602", 0x11B239C}, // from types.tsv uEm0602 vt=0x15b239c
    {18, "Giant Undead", "Undead", 0x23, -1, "uEm0603", 0x11B26C4}, // from types.tsv uEm0603 vt=0x15b26c4
    {19, "Harpies", "Harpy", 0x25, 19, "uEm0700", 0x11B4204}, // from types.tsv uEm0700 vt=0x15b4204
    {20, "Snow Harpies", "Harpy", 0x26, -1, "uEm0701", 0x11B483C}, // from types.tsv uEm0701 vt=0x15b483c
    {21, "Succubi", "Harpy", 0x27, -1, "uEm0702", 0x11B4B5C}, // from types.tsv uEm0702 vt=0x15b4b5c
    {22, "Gargoyles", "Gargoyle", 0x2C, -1, "uEm0900", 0x11B59A8}, // from types.tsv uEm0900 vt=0x15b59a8
    {23, "Phantoms", "Ghost", 0x37, -1, "uEm1200", 0x11B74AC}, // from types.tsv uEm1200 vt=0x15b74ac
    {24, "Phantasms", "Ghost", 0x38, -1, "uEm1201", 0x11B77CC}, // from types.tsv uEm1201 vt=0x15b77cc
    {25, "Specters", "Ghost", 0xFF, -1, "", 0}, // TODO: needs types.tsv/CT scan
    {26, "Hostile Soldiers", "Human", 0xE0, -1, "uHumanEnemy", 0x11EB494}, // FIXED: uHumanEnemy vtable
    {27, "Hostile Bandits", "Human", 0xE0, -1, "uHumanEnemy", 0x11EB494}, // FIXED: same uHumanEnemy, distinguished by Faction later
    {28, "Enemy Wizard", "Human", 0xB7, -1, "uEm9100", 0x116661C}, // from types.tsv uEm9100 vt=0x156661c
    {29, "Cyclopes", "Cyclops", 0x39, -1, "uEm2000", 0x11B8DF4}, // from types.tsv uEm2000 vt=0x15b8df4
    {30, "Ogres", "Ogre", 0x3A, -1, "uEm2001", 0x11B9124}, // from types.tsv uEm2001 vt=0x15b9124
    {31, "Golems", "Golem", 0x3F, -1, "uEm5000", 0x11BC400}, // from types.tsv uEm5000 vt=0x15bc400
    {32, "Metal Golems", "Golem", 0xFF, -1, "", 0}, // TODO: needs types.tsv/CT scan
    {33, "Chimeras", "Chimera", 0x4A, -1, "uEm5200", 0x11C0C58}, // from types.tsv uEm5200 vt=0x15c0c58
    {34, "Gorechimeras", "Chimera", 0x52, -1, "uEm5301", 0x11C3F6C}, // from types.tsv uEm5301 vt=0x15c3f6c
    {35, "Hydras", "Hydra", 0x54, -1, "uEm5400", 0x11C6CB4}, // from types.tsv uEm5400 vt=0x15c6cb4
    {36, "Archydras", "Hydra", 0x55, -1, "uEm5401", 0x11C6FDC}, // from types.tsv uEm5401 vt=0x15c6fdc
    {37, "Griffins", "Griffin", 0x5A, -1, "uEm5800", 0x11CF280}, // from types.tsv uEm5800 vt=0x15cf280
    {38, "Cockatrices", "Cockatrice", 0x5B, -1, "uEm5801", 0x11D1438}, // from types.tsv uEm5801 vt=0x15d1438
    {39, "Evil Eyes", "EvilEye", 0x5C, -1, "uEm5900", 0x11D2C74}, // from types.tsv uEm5900 vt=0x15d2c74
    {40, "Vile Eyes", "EvilEye", 0xB4, -1, "uEm5906", 0x11D3F64}, // from types.tsv uEm5906 vt=0x15d3f64
    {41, "Wights", "Wight", 0x5F, -1, "uEm6000", 0x11D51E8}, // from types.tsv uEm6000 vt=0x15d51e8
    {42, "Liches", "Lich", 0x60, -1, "uEm6001", 0x11D5508}, // from types.tsv uEm6001 vt=0x15d5508
    {43, "The Dragon (Grigori)", "Dragon", 0x61, -1, "uEm8000", 0x11D6410}, // from types.tsv uEm8000 vt=0x15d6410
    {44, "The Ur-Dragon", "Dragon", 0xFF, -1, "", 0}, // TODO: needs types.tsv/CT scan
    {45, "Drakes", "Dragon", 0x62, -1, "uEm8100", 0x11D6A10}, // from types.tsv uEm8100 vt=0x15d6a10
    {46, "Wyrms", "Dragon", 0x63, -1, "uEm8200", 0x11D7070}, // from types.tsv uEm8200 vt=0x15d7070
    {47, "Wyverns", "Dragon", 0x64, -1, "uEm8201", 0x11D7418}, // from types.tsv uEm8201 vt=0x15d7418
    {48, "The Seneschal", "Boss", 0x73, -1, "uEm8900", 0x11D9DE0}, // from types.tsv uEm8900 vt=0x15d9de0
    {49, "Enemy Person", "Human", 0xFF, -1, "", 0}, // TODO: needs types.tsv/CT scan
    {50, "Greater Goblins", "BBI-Goblin", 0xFF, -1, "", 0}, // TODO: needs types.tsv/CT scan
    {51, "Goblin Shamans", "BBI-Goblin", 0xFF, -1, "", 0}, // TODO: needs types.tsv/CT scan
    {52, "Wargs / Garm", "BBI-Wolf", 0xFF, -1, "", 0}, // TODO: needs types.tsv/CT scan
    {53, "Skeleton Brutes", "BBI-Skeleton", 0xFF, -1, "", 0}, // TODO: needs types.tsv/CT scan
    {54, "Golden Knights", "BBI-Skeleton", 0xFF, -1, "", 0}, // TODO: needs types.tsv/CT scan
    {55, "Silver Knights", "BBI-Skeleton", 0xFF, -1, "", 0}, // TODO: needs types.tsv/CT scan
    {56, "Living Armor", "BBI-Armor", 0xFF, -1, "", 0}, // TODO: needs types.tsv/CT scan
    {57, "Pyre Saurians", "BBI-Saurian", 0xFF, -1, "", 0}, // TODO: needs types.tsv/CT scan
    {58, "Poisoned Undead", "BBI-Undead", 0xFF, -1, "", 0}, // TODO: needs types.tsv/CT scan
    {59, "Banshees", "BBI-Undead", 0xFF, -1, "", 0}, // TODO: needs types.tsv/CT scan
    {60, "Eliminators", "BBI-Undead", 0xFF, -1, "", 0}, // TODO: needs types.tsv/CT scan
    {61, "Strigoi", "BBI-Harpy", 0xFF, -1, "", 0}, // TODO: needs types.tsv/CT scan
    {62, "Sirens", "BBI-Harpy", 0xFF, -1, "", 0}, // TODO: needs types.tsv/CT scan
    {63, "Wraiths", "BBI-Ghost", 0xFF, -1, "", 0}, // TODO: needs types.tsv/CT scan
    {64, "Gorecyclopes", "BBI-Cyclops", 0xAF, -1, "uEm5500C", 0x1163914}, // from types.tsv uEm5500C vt=0x1563914
    {65, "Elder Ogres", "BBI-Ogre", 0x44, -1, "uEm5501", 0x11CD780}, // from types.tsv uEm5501 vt=0x15cd780
    {66, "Gazers", "BBI-EvilEye", 0xFF, -1, "", 0}, // TODO: needs types.tsv/CT scan
    {67, "Maneaters", "BBI-Misc", 0xFF, -1, "", 0}, // TODO: needs types.tsv/CT scan
    {68, "Dark Bishops", "BBI-Wight", 0xFF, -1, "", 0}, // TODO: needs types.tsv/CT scan
    {69, "Death", "BBI-Boss", 0xFF, -1, "", 0}, // TODO: needs types.tsv/CT scan
    {70, "Cursed Dragons", "BBI-Dragon", 0xFF, -1, "", 0}, // TODO: needs types.tsv/CT scan
    {71, "Daimon", "BBI-Boss", 0xFF, -1, "", 0}, // TODO: needs types.tsv/CT scan
    {-1, nullptr, nullptr, 0, -1, nullptr, 0}
};

// Note: mStudyIdx -1 = not yet scanned. How to discover:
// 1. In game, kill 60 mobs of that type (need bestiary entry)
// 2. In CheatEngine, scan pawn + 0x1616[322] for changed byte (0->nonzero)
// 3. Put index into table above. See docs/TYPES_TSV_WALL_BREAKTHROUGH.md
