// CharParamEnemy.Generated.h - AUTOGENERATED from resources/extracted_assets/em0100/charparam/em/em0100_cmn.prp
// python3 tools/prp_to_header.py
// Не редактировать руками: правь таблицу имён в генераторе.
#pragma once
#include <stdint.h>

// cCharParamEnemy - загруженный в память em0100_cmn.prp (320 B).
// В теле uEm0100 лежит ДВУМЯ копиями подряд: +0x5870 и +0x59B0.
// Имена только ASCII: они идут в лог и в панель ImGui.
namespace CharParamEnemy {

static const uint32_t kSize      = 320;   // sizeof структуры
static const uint32_t kCopy0Off  = 0x5870; // первая копия в теле uEm0100
static const uint32_t kCopy1Off  = 0x59B0; // вторая (шаг = kSize)

// Типы XFS, которые встречаются в этом классе.
enum FieldType { kF32 = 0, kU32 = 1, kS32 = 2, kBool = 3, kVec3 = 4, kOther = 5 };

// off - смещение в РАНТАЙМ-структуре (не в файле!).
struct Field { uint16_t off; uint8_t type; uint8_t size; const char* name; };

static const int kCount = 67;
static const Field kFields[kCount] = {
    { 0x0000, kU32  ,  4, "_vtable" },
    { 0x0004, kU32  ,  4, "_flag" },
    { 0x0008, kU32  ,  4, "exp" },
    { 0x000C, kF32  ,  4, "attack" },
    { 0x0010, kF32  ,  4, "defense" },
    { 0x0014, kF32  ,  4, "magick_attack" },
    { 0x0018, kF32  ,  4, "magick_defense" },
    { 0x001C, kF32  ,  4, "weight" },
    { 0x0020, kU32  ,  4, "size_class" },
    { 0x0024, kU32  ,  4, "restraint_type" },
    { 0x0028, kU32  ,  4, "thrown_behaviour" },
    { 0x002C, kU32  ,  4, "wind_pressure_dmg" },
    { 0x0030, kBool ,  1, "ground_shake" },
    { 0x0031, kBool ,  1, "hugeable_disabled" },
    { 0x0034, kU32  ,  4, "inplace_restraint_type" },
    { 0x0038, kF32  ,  4, "res_fire" },
    { 0x003C, kF32  ,  4, "res_ice" },
    { 0x0040, kF32  ,  4, "res_thunder" },
    { 0x0044, kF32  ,  4, "res_holy" },
    { 0x0048, kF32  ,  4, "res_dark" },
    { 0x004C, kF32  ,  4, "res_slash" },
    { 0x0050, kF32  ,  4, "res_strike" },
    { 0x0054, kF32  ,  4, "res_poison" },
    { 0x0058, kF32  ,  4, "res_TORPOR" },
    { 0x005C, kF32  ,  4, "res_blind" },
    { 0x0060, kF32  ,  4, "res_sleep" },
    { 0x0064, kF32  ,  4, "res_tarred" },
    { 0x0068, kF32  ,  4, "res_drenched" },
    { 0x006C, kF32  ,  4, "res_possession" },
    { 0x0070, kF32  ,  4, "res_silence" },
    { 0x0074, kF32  ,  4, "res_skill_stifling" },
    { 0x0078, kF32  ,  4, "res_curse" },
    { 0x007C, kF32  ,  4, "res_burning" },
    { 0x0080, kF32  ,  4, "res_frozen" },
    { 0x0084, kF32  ,  4, "res_thunderstruck" },
    { 0x0088, kF32  ,  4, "res_holy_ex" },
    { 0x008C, kF32  ,  4, "res_dark_ex" },
    { 0x0090, kF32  ,  4, "res_petrify" },
    { 0x0094, kF32  ,  4, "res_atk_down" },
    { 0x0098, kF32  ,  4, "res_def_down" },
    { 0x009C, kF32  ,  4, "res_matk_down" },
    { 0x00A0, kF32  ,  4, "res_mdef_down" },
    { 0x00C0, kVec3 , 16, "base_point_offset" },
    { 0x00D0, kU32  ,  4, "path_size" },
    { 0x00D4, kU32  ,  4, "obj_correct_size" },
    { 0x00D8, kU32  ,  4, "suction_size" },
    { 0x00DC, kF32  ,  4, "human_hp" },
    { 0x00E0, kF32  ,  4, "human_flinch_endur" },
    { 0x00E4, kF32  ,  4, "human_knockdown_endur" },
    { 0x00E8, kU32  ,  4, "cam_near_index" },
    { 0x00EC, kF32  ,  4, "cam_near_dist" },
    { 0x00F0, kU32  ,  4, "cam_mid_index" },
    { 0x00F4, kF32  ,  4, "cam_mid_dist" },
    { 0x00F8, kU32  ,  4, "cam_far_index" },
    { 0x00FC, kF32  ,  4, "cam_far_dist" },
    { 0x0100, kF32  ,  4, "return_activate_time" },
    { 0x0104, kF32  ,  4, "return_duration_time" },
    { 0x0108, kF32  ,  4, "fall_height" },
    { 0x010C, kF32  ,  4, "fall_damage_height" },
    { 0x0110, kF32  ,  4, "fall_death_height" },
    { 0x0114, kF32  ,  4, "fall_damage_pct" },
    { 0x0118, kF32  ,  4, "sink_corpse_dist" },
    { 0x011C, kF32  ,  4, "sink_se_off_dist" },
    { 0x0120, kF32  ,  4, "RESTRAINT_SLOW_LV1" },
    { 0x0124, kF32  ,  4, "RESTRAINT_SLOW_LV2" },
    { 0x0128, kF32  ,  4, "RESTRAINT_SLOW_EX" },
    { 0x012C, kF32  ,  4, "scale" },
};

// Имя поля по смещению внутри структуры. Пустая строка = смещение
// не совпадает с началом поля (середина vector3, дырка выравнивания).
inline const char* LabelAt(uint32_t off)
{
    for (int i = 0; i < kCount; ++i)
        if (kFields[i].off == off) return kFields[i].name;
    return "";
}

} // namespace CharParamEnemy
